# Lade die CSV-Dateien

```{r}
# install.packages("ranger")
# install.packages("dplyr")
# install.packages("caret")

library(ranger)
library(caret)
library(dplyr)
```

```{r}
set.seed(069)
```

```{r}

house_prices <- read.csv("./resources/house_prices.csv")

random_indices <- sample(1:nrow(house_prices))
house_prices <- house_prices[random_indices, ]
train_index <- createDataPartition(house_prices$SalePrice, p = 0.8, list = FALSE)
train_set <- house_prices[train_index, ] # 80% of the datase
test_set <- house_prices[-train_index, ]

```

```{r}
# # Define the grid of parameters to search over
# num_trees <- c(500, 1000, 1500)
# sample_fraction <- c(0.632, 0.8, 1)
# mtry <- c(2, 3, 4)
# replace <- c(TRUE, FALSE)
# min_bucket <- c(1, 5, 10)

# grid <- expand.grid(
#   num.trees = num_trees,
#   sample.fraction = sample_fraction,
#   mtry = mtry
#   # replace = replace,
#   # min.bucket = min_bucket
# )

# # Initialize a data frame to store the results
# results_frame <- data.frame(
#   num.trees = numeric(),
#   sample.fraction = numeric(),
#   mtry = numeric(),
#   replace = logical(),
#   min.bucket = numeric(),

#   mse = numeric(),
#   runtime_training = numeric(),
#   runtime_prediction = numeric()
# )

# # Loop over the grid of parameters
# for (i in 1:nrow(grid)) {
  
#   runtime_training <- system.time({
#     model <- ranger::ranger(
#     SalePrice ~ .,
#     data = train_set,
#     num.trees = grid$num.trees[i],
#     sample.fraction = grid$sample.fraction[i],
#     mtry = grid$mtry[i]
#     # replace = grid$replace[i],
#     # min.bucket = grid$min.bucket[i]
#   )
#   })[3] # [3]rd is the elapsed time
  
#   print(model)

#   print(paste("Successfully trained hyperparameter combination: ",
#               grid$num.trees[i],
#               grid$sample.fraction[i],
#               grid$mtry[i]
#               # grid$mtry[i], grid$replace[i]
#               # grid$min.bucket[i]
#         )
#     )

#   runtime_prediction <- system.time({
#     pred <- predict(model, test_set[, colnames(test_set) != "SalePrice"])
#     errors <- pred$predictions - test_set$SalePrice
#     squared_errors <- errors^2
#     mse <- mean(squared_errors)
#     })[3] # [3]rd element is the elapsed time

#   # Store the results
#   results <- rbind(results, data.frame(
#     num.trees = grid$num.trees[i],
#     sample.fraction = grid$sample.fraction[i],
#     mtry = grid$mtry[i],
#     # replace = grid$replace[i],
#     # min.bucket = grid$min.bucket[i],
#     mse = mse,
#     runtime_training = runtime_training,
#     runtime_prediction = runtime_prediction
#   ))
# }
```

```{r}
# print(results)
```

```{r}
# Find the best parameters
# best_params <- results %>%
#   filter(mse == min(mse)) %>%
#   select(num.trees, sample.fraction) # , mtry, replace, min.bucket)

# print(best_params)
```

```{r}
# write.csv(results, file = "./resources/results.csv")
```

# Random Search all parameters
```{r}
# Define the boundaries for RandomSearch
num_trees_lower <- 2
num_trees_upper <- 2048
mtry_lower <- 1
mtry_upper <- 60
sample_fraction_lower <- 0.1
sample_fraction_upper <- 1
min_node_size_lower <- 1
min_node_size_upper <- 50
replace_lower <- FALSE
replace_upper <- TRUE

num_evals <- 50
```

```{r}
# grid for 5 params
random_distributed_grid <- data.frame(
  num_trees = round(runif(num_evals, num_trees_lower, num_trees_upper)),
  mtry = round(runif(num_evals, mtry_lower, mtry_upper)),
  sample_fraction = runif(num_evals, sample_fraction_lower, sample_fraction_upper),
  min_node_size = round(runif(num_evals, min_node_size_lower, min_node_size_upper)),
  replace = sample(c(replace_lower, replace_upper), num_evals, replace = TRUE)
)
```

```{r}
# Initialize a data frame to store the results
results_frame <- data.frame(
  num_trees = numeric(),
  sample_fraction = numeric(),
  mtry = numeric(),
  replace = logical(),
  min_node_size = numeric(),

  mse = numeric(),
  runtime_training = numeric(),
  runtime_prediction = numeric()
)

# Loop over the grid of parameters
for (i in seq_len(nrow(random_distributed_grid))) {
  num_trees = random_distributed_grid[i, "num_trees"]
  sample_fraction = random_distributed_grid[i, "sample_fraction"]
  mtry = random_distributed_grid[i, "mtry"]
  replace = random_distributed_grid[i, "replace"]
  min_node_size = random_distributed_grid[i, "min_node_size"]

  runtime_training <- system.time({
    model <- ranger::ranger(
    SalePrice ~ .,
    data = train_set,
    num.trees =num_trees,
    sample.fraction = sample_fraction,
    mtry = mtry,
    replace = replace,
    min.node.size = min_node_size
  )
  })[3] # [3]rd is the elapsed time

  print(paste("Successfully trained hyperparameter combination: ",
              min_node_size,
              sample_fraction,
              mtry,
              replace,
              min_node_size
        )
    )

  runtime_prediction <- system.time({
    pred <- predict(model, test_set[, colnames(test_set) != "SalePrice"])
    errors <- pred$predictions - test_set$SalePrice
    squared_errors <- errors^2
    mse <- mean(squared_errors)
    })[3] # [3]rd element is the elapsed time

  # Ensure all variables are of length 1
  num_trees <- as.numeric(num_trees)
  sample_fraction <- as.numeric(sample_fraction)
  mtry <- as.numeric(mtry)
  replace <- as.logical(replace)
  min_node_size <- as.numeric(min_node_size)
  mse <- as.numeric(mse)
  runtime_training <- as.numeric(runtime_training)
  runtime_prediction <- as.numeric(runtime_prediction)

  # Store the results
  results_frame <- rbind(results_frame, data.frame(
    num_trees = num_trees,
    sample_fraction = sample_fraction,
    mtry = mtry,
    replace = replace,
    min_node_size = min_node_size,
    mse = mse,
    runtime_training = runtime_training,
    runtime_prediction = runtime_prediction
  ))
}
# write.csv(results_random_search, file = "./resources/results_all_random/results.csv")
```

```{r}

num_evals <- 5

# Pair 1: num_trees and mtry
random_num_trees_mtry <- data.frame(
  num_trees = round(runif(num_evals, num_trees_lower, num_trees_upper)),
  mtry = round(runif(num_evals, mtry_lower, mtry_upper))
)

# Pair 2: num_trees and sample_fraction
random_num_trees_sample_fraction <- data.frame(
  num_trees = round(runif(num_evals, num_trees_lower, num_trees_upper)),
  sample_fraction = runif(num_evals, sample_fraction_lower, sample_fraction_upper)
)

# Pair 3: num_trees and min_node_size
random_num_trees_min_node_size <- data.frame(
  num_trees = round(runif(num_evals, num_trees_lower, num_trees_upper)),
  min_node_size = round(runif(num_evals, min_node_size_lower, min_node_size_upper))
)

# Pair 4: num_trees and replace
random_num_trees_replace <- data.frame(
  num_trees = round(runif(num_evals, num_trees_lower, num_trees_upper)),
  replace = sample(c(replace_lower, replace_upper), num_evals, replace = TRUE)
)

# Pair 5: mtry and sample_fraction
random_mtry_sample_fraction <- data.frame(
  mtry = round(runif(num_evals, mtry_lower, mtry_upper)),
  sample_fraction = runif(num_evals, sample_fraction_lower, sample_fraction_upper)
)

# Pair 6: mtry and min_node_size
random_mtry_min_node_size <- data.frame(
  mtry = round(runif(num_evals, mtry_lower, mtry_upper)),
  min_node_size = round(runif(num_evals, min_node_size_lower, min_node_size_upper))
)

# Pair 7: mtry and replace
random_mtry_replace <- data.frame(
  mtry = round(runif(num_evals, mtry_lower, mtry_upper)),
  replace = sample(c(replace_lower, replace_upper), num_evals, replace = TRUE)
)

# Pair 8: sample_fraction and min_node_size
random_sample_fraction_min_node_size <- data.frame(
  sample_fraction = runif(num_evals, sample_fraction_lower, sample_fraction_upper),
  min_node_size = round(runif(num_evals, min_node_size_lower, min_node_size_upper))
)

# Pair 9: sample_fraction and replace
random_sample_fraction_replace <- data.frame(
  sample_fraction = runif(num_evals, sample_fraction_lower, sample_fraction_upper),
  replace = sample(c(replace_lower, replace_upper), num_evals, replace = TRUE)
)

# Pair 10: min_node_size and replace
random_min_node_size_replace <- data.frame(
  min_node_size = round(runif(num_evals, min_node_size_lower, min_node_size_upper)),
  replace = sample(c(replace_lower, replace_upper), num_evals, replace = TRUE)
)

# list of all dataframes
random_distributed_frames <- list(
  random_num_trees_mtry,
  random_num_trees_sample_fraction,
  random_num_trees_min_node_size,
  random_num_trees_replace,
  random_mtry_sample_fraction,
  random_mtry_min_node_size,
  random_mtry_replace,
  random_sample_fraction_min_node_size,
  random_sample_fraction_replace,
  random_min_node_size_replace
)
```

```{r}

# loop through all frames
for (frame in random_distributed_frames) {
  name_param_1 <- colnames(frame)[1]
  name_param_2 <- colnames(frame)[2]
  df_name <- paste(name_param_1, name_param_2, sep = "_")
  arg_name_param1 <- gsub("_", ".", name_param_1)
  arg_name_param2 <- gsub("_", ".", name_param_2)

  args <- list(
    formula = SalePrice ~ .,
    data = train_set
  )

  results_frame <- data.frame(
    num_trees = numeric(),
    sample_fraction = numeric(),
    mtry = numeric(),
    replace = logical(),
    min_node_size = numeric(),
    mse = numeric(),
    runtime_training = numeric(),
    runtime_prediction = numeric()
  )

# Access data in each frame
  for (i in 1:nrow(frame)) {
    args[[arg_name_param1]] <- frame[i, name_param_1]
    args[[arg_name_param2]] <- frame[i, name_param_2]

    # Call the ranger function with the arguments
    runtime_training <- system.time({
      model <- do.call(ranger::ranger, args)
    })[3]

    runtime_prediction <- system.time({
      pred <- predict(model, test_set[, colnames(test_set) != "SalePrice"])
      errors <- pred$predictions - test_set$SalePrice
      squared_errors <- errors^2
      mse <- mean(squared_errors)
    })[3]

    # Store the results
    results <- list(
      num_trees = NA,
      sample_fraction = NA,
      mtry = NA,
      replace = NA,
      min_node_size = NA,
      mse = mse,
      runtime_training = runtime_training,
      runtime_prediction = runtime_prediction
    )

    results[[name_param_1]] <- frame[i, name_param_1]
    results[[name_param_2]] <- frame[i, name_param_2]
    results_frame <- rbind(results_frame, as.data.frame(t(unlist(results))))

    print(paste("Successfully trained hyperparameter combination: ", 
                name_param_1, ": ", frame[i, name_param_1], "and",
                name_param_2, ": ", frame[i, name_param_2], ,
                "with mse: ", mse, "and runtime: ", runtime_training, "seconds."
          )
          )
  }

  # Write the results to a CSV file
  write.csv(results_frame, file = paste0("./resources/results_pairwise_random/", df_name, ".csv"))
  print("--------------------")
  print(paste("Successfully wrote", df_name, "to file: ", paste0("./resources/results_pairwise_random/", df_name, ".csv")))
  print("--------------------")
}
```



```{r}

results_frame <- data.frame(
  num_trees = numeric(),
  sample_fraction = numeric(),
  mtry = numeric(),
  replace = logical(),
  min_node_size = numeric(),
  mse = numeric(),
  runtime_training = numeric(),
  runtime_prediction = numeric()
)

df_name <- "num_trees_mtry"
print(paste0("./resources/results_pairwise_random/", df_name, ".csv"))
write.csv(results_frame, file = paste0("./resources/results_pairwise_random/", df_name, ".csv"))

```