# Lade die CSV-Dateien

```{r}
# install.packages("ranger")
# install.packages("dplyr")
# install.packages("caret")

library(ranger)
library(caret)
library(dplyr)
```

```{r}
set.seed(069)
```

```{r}

house_prices <- read.csv("./resources/house_prices.csv")

random_indices <- sample(1:nrow(house_prices))
house_prices <- house_prices[random_indices, ]
train_index <- createDataPartition(house_prices$SalePrice, p = 0.8, list = FALSE)
train_set <- house_prices[train_index, ] # 80% of the datase
test_set <- house_prices[-train_index, ]

```

```{r}
# Define the grid of parameters to search over

num_trees <- c(500, 1000, 1500)
sample_fraction <- c(0.632, 0.8, 1)
mtry <- c(2, 3, 4)
replace <- c(TRUE, FALSE)
min_bucket <- c(1, 5, 10)

grid <- expand.grid(
  num.trees = num_trees,
  sample.fraction = sample_fraction#,
  # mtry = mtry,
  # replace = replace,
  # min.bucket = min_bucket
)

# Initialize a data frame to store the results
results <- data.frame(
  num.trees = numeric(),
  sample.fraction = numeric(),
  mtry = numeric(),
  replace = logical(),
  min.bucket = numeric(),

  mse = numeric(),
  runtime_training = numeric(),
  runtime_prediction = numeric()
)

```

```{r}

# Loop over the grid of parameters
for (i in 1:nrow(grid)) {
  
  runtime_training <- system.time({
    model <- ranger::ranger(
    SalePrice ~ .,
    data = train_set,
    num.trees = grid$num.trees[i],
    sample.fraction = grid$sample.fraction[i],
    # mtry = grid$mtry[i],
    # replace = grid$replace[i],
    # min.bucket = grid$min.bucket[i]
  )
  })[3] # [3]rd is the elapsed time
  
  print(paste("Successfully trained hyperparameter combination: ",
              grid$num.trees[i],
              grid$sample.fraction[i]#,
              # grid$mtry[i], grid$replace[i],
              # grid$min.bucket[i]
        )
    )

  runtime_prediction <- system.time({
    pred <- predict(model, test_set[, colnames(test_set) != "SalePrice"])
    errors <- pred$predictions - test_set$SalePrice
    squared_errors <- errors^2
    mse <- mean(squared_errors)
    })[3] # [3]rd element is the elapsed time

  # Store the results
  results <- rbind(results, data.frame(
    num.trees = grid$num.trees[i],
    sample.fraction = grid$sample.fraction[i],
    # mtry = grid$mtry[i],
    # replace = grid$replace[i],
    # min.bucket = grid$min.bucket[i],
    mse = mse,
    runtime_training = runtime_training,
    runtime_prediction = runtime_prediction
  ))
}
```

```{r}
print(results)
```

```{r}
# Find the best parameters
best_params <- results %>%
  filter(mse == min(mse)) %>%
  select(num.trees, sample.fraction) # , mtry, replace, min.bucket)

print(best_params)
```

```{r}
# write.csv(results, file = "./resources/results.csv")
```